name: codecrafters-redis
version: 0.1.0.0
license: BSD3
author: Olaoluwa Mustapha
synopsis: Redis server implementation in Haskell

extra-source-files:
  - README.md

language: GHC2021
dependencies:
  - base >= 4.7 && < 5
  - binary
  - binary-instances
  - bits-show
  - bytestring # useful to send bytes over the network
  - containers
  - data-default
  - mono-traversable
  - mtl
  - network
  - pretty-simple
  - stm
  - string-interpolate
  - text
  - time

default-extensions:
  - AllowAmbiguousTypes
  - ApplicativeDo
  - BlockArguments
  - DataKinds
  - DeriveAnyClass
  - DerivingStrategies
  - DerivingVia
  - DuplicateRecordFields
  - FunctionalDependencies
  - GADTs
  - ImportQualifiedPost
  - LambdaCase
  - NamedFieldPuns
  - NoFieldSelectors
  - NoStarIsType
  - OverloadedRecordDot
  - OverloadedLabels
  - OverloadedStrings
  - PackageImports
  - PatternSynonyms
  - QuasiQuotes
  - RecordWildCards
  - StrictData
  - TemplateHaskell
  - TypeApplications

ghc-options:
  - -Wall
  - -Wmissing-export-lists
  - -Wmissing-deriving-strategies
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints
  - -Wno-unused-top-binds

executables:
  codecrafters-redis-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - async
      - codecrafters-redis
      - envparse
      - network-run
      - optparse-applicative
      - split

benchmarks:
  codecrafters-redis-benchmarks:
    main: Main.hs
    source-dirs: bench
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - codecrafters-redis
      - criterion

library:
  source-dirs: src
  dependencies:
    - aeson
    - async # may help with concurrency
    - attoparsec
    - Blammo
    - codecrafters-redis-ffi
    - deepseq
    - envparse
    - extra
    - exceptions
    - filepath
    - Glob
    - hashable
    # - heap # For modelling other redis data structures
    - optics
    - optparse-applicative
    - parser-combinators
    - path
    - prettyprinter
    - rerefined
    - safe
    - safe-exceptions
    - split
    - stm
    - tagged
    - template-haskell
    - unordered-containers
    - utf8-string
    - vector

tests:
  codecrafters-redis-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -Wno-missing-export-lists
      - -Wno-x-unsafe-internals
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - attoparsec
      - Blammo
      - codecrafters-redis
      - directory
      - filepath
      - hspec
      - hspec-golden
      - hspec-hedgehog
      - hedgehog
      - optics
      - path
      - rerefined
      - tagged
      - tasty
      - tasty-discover
      - tasty-expected-failure
      - tasty-golden
      - tasty-hspec
      - tasty-hedgehog
      - tasty-hunit
      - unordered-containers
      - vector
