name: redis-haskell
version: 0.1.0.0
license: BSD3
author: Olaoluwa Mustapha
synopsis: Redis server implementation in Haskell

language: GHC2021
dependencies:
  - base
  - bytestring # useful to send bytes over the network
  - containers
  - concurrency
  - data-default
  - string-interpolate
  - text

default-extensions:
  - AllowAmbiguousTypes
  - ApplicativeDo
  - BlockArguments
  - DeriveAnyClass
  - DerivingStrategies
  - DerivingVia
  - DuplicateRecordFields
  - FunctionalDependencies
  - GADTs
  - ImportQualifiedPost
  - LambdaCase
  - NamedFieldPuns
  - NoFieldSelectors
  - NoStarIsType
  - OverloadedRecordDot
  - OverloadedStrings
  - PackageImports
  - PatternSynonyms
  - QuasiQuotes
  - RecordWildCards
  - StrictData
  - TypeApplications

ghc-options:
  - -Wall
  - -Wmissing-export-lists
  - -Wmissing-deriving-strategies
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints
  - -Wno-unused-top-binds

executables:
  redis-haskell-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - async
      - redis-haskell
      - mtl
      - network # required when using bytestring
      - network-run
      - split
      - stm
      - time

library:
  source-dirs: src
  dependencies:
    - aeson
    - async # may help with concurrency
    - attoparsec
    - Blammo
    - dejafu
    - errors
    - extra
    - lens
    - monoidal-containers
    - mtl
    - network # required when using bytestring
    - optparse-applicative
    - parser-combinators
    - safe
    - semialign
    - split
    - stm # may help with a concurrent database
    - these
    - time
    - transformers
    - unliftio
    - unordered-containers
    - unix-time
    - vector

tests:
  redis-haskell-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -Wno-missing-export-lists
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - attoparsec
      - Blammo
      - redis-haskell
      - hspec
      - hedgehog
      - lens
      - mtl
      - network
      - tasty
      - tasty-discover
      - tasty-expected-failure
      - tasty-hspec
      - tasty-hedgehog
      - transformers
      - vector
