name: codecrafters-redis
version: 0.1.0.0
license: BSD3
author: Olaoluwa Mustapha
synopsis: Redis server implementation in Haskell

extra-source-files:
  - README.md

language: GHC2021
dependencies:
  - base
  - binary
  - binary-instances
  - bits-show
  - bytestring # useful to send bytes over the network
  - containers
  - data-default
  - mono-traversable
  - mtl
  - network
  - pretty-simple
  - stm
  - string-interpolate
  - text
  - text-ascii
  - time

default-extensions:
  - AllowAmbiguousTypes
  - ApplicativeDo
  - BlockArguments
  - DataKinds
  - DeriveAnyClass
  - DerivingStrategies
  - DerivingVia
  - DuplicateRecordFields
  - FunctionalDependencies
  - GADTs
  - ImportQualifiedPost
  - LambdaCase
  - NamedFieldPuns
  - NoFieldSelectors
  - NoStarIsType
  - OverloadedRecordDot
  - OverloadedLabels
  - OverloadedStrings
  - PackageImports
  - PatternSynonyms
  - QuasiQuotes
  - RecordWildCards
  - StrictData
  - TypeApplications

ghc-options:
  - -Wall
  - -Wmissing-export-lists
  - -Wmissing-deriving-strategies
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints
  - -Wno-unused-top-binds

executables:
  codecrafters-redis-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - async
      - codecrafters-redis
      - envparse
      - network-run
      - optparse-applicative
      - split

library:
  source-dirs: src
  include-dirs:
    - include/crc64_redis
    - include/liblzf
  c-sources:
    - include/crc64_redis/*.c
    - include/liblzf/*.c
  dependencies:
    - aeson
    - async # may help with concurrency
    - attoparsec
    - Blammo
    - deepseq
    - envparse
    - extra
    - filepath
    - Glob
    # - heap # For modelling other redis data structures
    - optics
    - optparse-applicative
    - parser-combinators
    - safe
    - split
    - stm
    - tagged
    - template-haskell
    - unordered-containers
    - utf8-string
    - vector

tests:
  codecrafters-redis-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -Wno-missing-export-lists
      - -Wno-x-unsafe-internals
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - attoparsec
      - Blammo
      - codecrafters-redis
      - directory
      - filepath
      - hspec
      - hedgehog
      - optics
      - tagged
      - tasty
      - tasty-discover
      - tasty-expected-failure
      - tasty-hspec
      - tasty-hedgehog
      - unordered-containers
      - vector
