# DON'T EDIT THIS!
#
# Codecrafters relies on this file being intact to run tests successfully. Any changes
# here will not reflect when CodeCrafters tests your code, and might even cause build
# failures.
#
# DON'T EDIT THIS!
resolver: lts-23.18

packages:
  - codecrafters-redis
  - codecrafters-redis-ffi

extra-deps:
  - text-ascii-1.2.1
  - git: https://github.com/OlaoluwaM/bits-show.git
    commit: b96614a3a361156e39441190d8d9fe7cbd8ff29a
    subdirs:
      - bits-show
